[package]
name = "dmn-void-src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.3"
serde = "1.0.203"
serde_derive = "1.0.203"
toml = "0.8.14"
url = "2.5.1"
